# Generated by Django 6.0.3 on 2026-03-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NautilusConsultationModel',
            fields=[
                ('ConsultationID', models.IntegerField(db_column='ConsultationID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='Firstname', max_length=20)),
                ('lastname', models.CharField(db_column='Lastname', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('phone', models.CharField(db_column='Phone', max_length=20)),
                ('message', models.TextField(db_column='Message')),
                ('lawType', models.CharField(db_column='LawType', max_length=20)),
            ],
            options={
                'db_table': 'consultation',
            },
        ),
        migrations.CreateModel(
            name='NautilusReviewModel',
            fields=[
                ('reviewid', models.IntegerField(db_column='ReviewID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='Firstname', max_length=20)),
                ('lastname', models.CharField(db_column='Lastname', max_length=20)),
                ('message', models.TextField(db_column='Message')),
                ('rating', models.CharField(db_column='Rating', max_length=20)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='NautilusTeamModel',
            fields=[
                ('TeamID', models.IntegerField(db_column='TeamID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='Firstname', max_length=20)),
                ('lastname', models.CharField(db_column='Lastname', max_length=20)),
                ('lawField', models.CharField(db_column='LawField', max_length=20)),
                ('teamPhoto', models.CharField(db_column='TeamPhoto', max_length=255)),
            ],
            options={
                'db_table': 'team',
            },
        ),
    ]
