# Generated by Django 6.0.3 on 2026-03-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautilus_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nautilusreviewmodel',
            name='reviewid',
            field=models.AutoField(db_column='ReviewID', primary_key=True, serialize=False),
        ),
    ]
