# Generated by Django 6.0.3 on 2026-03-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautilus_app', '0002_alter_nautilusreviewmodel_reviewid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nautilusconsultationmodel',
            name='ConsultationID',
            field=models.AutoField(db_column='ConsultationID', primary_key=True, serialize=False),
        ),
    ]
